import type { CompanySettings, Customer, ItemTemplate, Project } from "@/types";

export const dashboardStats = {
  monthlyRevenue: 2840000,
  unbilledCount: 4,
  unpaidCount: 3,
  activeProjects: 12,
};

export const unbilledProjects: Project[] = [
  {
    id: "p1",
    projectName: "コーポレートサイトリニューアル",
    customerName: "株式会社サンプル",
    status: "completed",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 880000,
    dueDate: "2026-05-20",
    nextAction: "請求書を作成する",
  },
  {
    id: "p2",
    projectName: "LP制作（春キャンペーン）",
    customerName: "合同会社グリーン",
    status: "completed",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 330000,
    dueDate: "2026-05-22",
    nextAction: "請求書を作成する",
  },
  {
    id: "p3",
    projectName: "動画編集（商品紹介）",
    customerName: "有限会社アート",
    status: "in_progress",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 165000,
    dueDate: "2026-05-28",
    nextAction: "作業完了後に請求",
  },
];

export const unpaidProjects: Project[] = [
  {
    id: "p4",
    projectName: "月額保守（5月分）",
    customerName: "株式会社テック",
    status: "completed",
    billingStatus: "billed",
    paymentStatus: "unpaid",
    amount: 6600,
    dueDate: "2026-05-15",
    nextAction: "入金確認をする",
  },
  {
    id: "p5",
    projectName: "店舗看板デザイン",
    customerName: "山田商店",
    status: "completed",
    billingStatus: "billed",
    paymentStatus: "unpaid",
    amount: 220000,
    dueDate: "2026-05-10",
    nextAction: "入金確認をする",
  },
  {
    id: "p6",
    projectName: "コンサルティング（4月）",
    customerName: "株式会社ビジョン",
    status: "completed",
    billingStatus: "overdue",
    paymentStatus: "overdue",
    amount: 550000,
    dueDate: "2026-04-30",
    nextAction: "督促・入金確認",
  },
];

export const overdueProjects: Project[] = [
  {
    id: "p6",
    projectName: "コンサルティング（4月）",
    customerName: "株式会社ビジョン",
    status: "completed",
    billingStatus: "overdue",
    paymentStatus: "overdue",
    amount: 550000,
    dueDate: "2026-04-30",
    nextAction: "督促・入金確認",
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    projectName: "コーポレートサイトリニューアル",
    customerName: "株式会社サンプル",
    status: "completed",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 880000,
    dueDate: "2026-05-20",
    nextAction: "請求書を作成する",
  },
  {
    id: "p2",
    projectName: "LP制作（春キャンペーン）",
    customerName: "合同会社グリーン",
    status: "completed",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 330000,
    dueDate: "2026-05-22",
    nextAction: "請求書を作成する",
  },
  {
    id: "p7",
    projectName: "ECサイト構築",
    customerName: "株式会社ネクスト",
    status: "quote_sent",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 1200000,
    dueDate: "2026-06-15",
    nextAction: "見積のフォローアップ",
  },
  {
    id: "p8",
    projectName: "ブランディング設計",
    customerName: "スタートアップ合同会社",
    status: "considering",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 450000,
    dueDate: "2026-06-01",
    nextAction: "顧客への確認連絡",
  },
  {
    id: "p9",
    projectName: "オフィスリフォーム設計",
    customerName: "株式会社建設",
    status: "ordered",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 2500000,
    dueDate: "2026-07-30",
    nextAction: "キックオフミーティング",
  },
  {
    id: "p3",
    projectName: "動画編集（商品紹介）",
    customerName: "有限会社アート",
    status: "in_progress",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 165000,
    dueDate: "2026-05-28",
    nextAction: "納品・完了処理",
  },
  {
    id: "p10",
    projectName: "税務相談（5月）",
    customerName: "田中一郎",
    status: "before_quote",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 0,
    dueDate: "2026-05-25",
    nextAction: "見積を作成する",
  },
  {
    id: "p4",
    projectName: "月額保守（5月分）",
    customerName: "株式会社テック",
    status: "completed",
    billingStatus: "billed",
    paymentStatus: "unpaid",
    amount: 6600,
    dueDate: "2026-05-15",
    nextAction: "入金確認をする",
  },
  {
    id: "p11",
    projectName: "SNS運用代行",
    customerName: "カフェ・モーニング",
    status: "completed",
    billingStatus: "billed",
    paymentStatus: "paid",
    amount: 88000,
    dueDate: "2026-04-30",
    nextAction: "—",
  },
  {
    id: "p12",
    projectName: "アプリUIデザイン",
    customerName: "株式会社モバイル",
    status: "lost",
    billingStatus: "unbilled",
    paymentStatus: "unpaid",
    amount: 600000,
    dueDate: "2026-04-15",
    nextAction: "—",
  },
];

export const customers: Customer[] = [
  {
    id: "c1",
    customerName: "株式会社サンプル",
    contactName: "佐藤 太郎",
    email: "sato@sample.co.jp",
    phone: "03-1234-5678",
    address: "東京都渋谷区1-2-3",
    projectCount: 3,
  },
  {
    id: "c2",
    customerName: "合同会社グリーン",
    contactName: "鈴木 花子",
    email: "suzuki@green.co.jp",
    phone: "03-9876-5432",
    address: "東京都港区4-5-6",
    projectCount: 2,
  },
  {
    id: "c3",
    customerName: "株式会社テック",
    contactName: "高橋 健",
    email: "takahashi@tech.co.jp",
    phone: "06-1111-2222",
    address: "大阪府大阪市7-8-9",
    projectCount: 5,
  },
  {
    id: "c4",
    customerName: "山田商店",
    contactName: "山田 一郎",
    email: "yamada@shop.jp",
    phone: "052-333-4444",
    address: "愛知県名古屋市10-11-12",
    projectCount: 1,
  },
  {
    id: "c5",
    customerName: "株式会社ビジョン",
    contactName: "伊藤 美咲",
    email: "ito@vision.co.jp",
    phone: "03-5555-6666",
    address: "東京都千代田区13-14-15",
    projectCount: 4,
  },
  {
    id: "c6",
    customerName: "有限会社アート",
    contactName: "渡辺 誠",
    email: "watanabe@art.jp",
    phone: "03-7777-8888",
    address: "東京都目黒区16-17-18",
    projectCount: 2,
  },
];

export const itemTemplates: ItemTemplate[] = [
  {
    id: "t1",
    name: "HP制作",
    category: "Web制作",
    description: "コーポレートサイト制作（10ページ程度）",
    unitPrice: 500000,
    taxRate: 10,
    isFavorite: true,
  },
  {
    id: "t2",
    name: "LP制作",
    category: "Web制作",
    description: "ランディングページ1ページ制作",
    unitPrice: 200000,
    taxRate: 10,
    isFavorite: true,
  },
  {
    id: "t3",
    name: "動画制作",
    category: "動画",
    description: "プロモーション動画（3分以内）",
    unitPrice: 150000,
    taxRate: 10,
    isFavorite: true,
  },
  {
    id: "t4",
    name: "月額保守",
    category: "保守",
    description: "サーバー・CMS保守（月額）",
    unitPrice: 6600,
    taxRate: 10,
    isFavorite: true,
  },
  {
    id: "t5",
    name: "施工費",
    category: "建築",
    description: "現場施工一式",
    unitPrice: 0,
    taxRate: 10,
    isFavorite: false,
  },
  {
    id: "t6",
    name: "材料費",
    category: "建築",
    description: "資材・材料費（実費精算）",
    unitPrice: 0,
    taxRate: 10,
    isFavorite: false,
  },
  {
    id: "t7",
    name: "デザイン費",
    category: "デザイン",
    description: "グラフィック・UIデザイン",
    unitPrice: 80000,
    taxRate: 10,
    isFavorite: false,
  },
  {
    id: "t8",
    name: "現地調査費",
    category: "建築",
    description: "現地調査・測量",
    unitPrice: 30000,
    taxRate: 10,
    isFavorite: false,
  },
  {
    id: "t9",
    name: "コンサルティング",
    category: "士業・コンサル",
    description: "業務改善コンサル（1時間）",
    unitPrice: 25000,
    taxRate: 10,
    isFavorite: true,
  },
  {
    id: "t10",
    name: "税務相談",
    category: "士業・コンサル",
    description: "税務相談（1時間）",
    unitPrice: 20000,
    taxRate: 10,
    isFavorite: false,
  },
];

export const companySettings: CompanySettings = {
  companyName: "株式会社クリエイトスタジオ",
  postalCode: "150-0001",
  address: "東京都渋谷区神宮前1-2-3 クリエイトビル4F",
  phone: "03-1234-5678",
  email: "info@createstudio.co.jp",
  invoiceNumber: "T1234567890123",
  bankName: "みずほ銀行",
  bankBranch: "渋谷支店",
  bankAccountType: "普通",
  bankAccountNumber: "1234567",
  bankAccountHolder: "カ）クリエイトスタジオ",
};
